# Generated by Django 6.1.1 on 2026-09-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre del Elemento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción Corta')),
                ('prioridad', models.IntegerField(default=1, verbose_name='Prioridad (Número)')),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Costo / Valor Decimal')),
                ('nivel_dificultad', models.CharField(choices=[('BAS', 'Básico'), ('INT', 'Intermedio'), ('ADV', 'Avanzado')], default='BAS', max_length=3, verbose_name='Nivel de Dificultad')),
                ('completado', models.BooleanField(default=False, verbose_name='¿Completado?')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Registro de Prueba',
                'verbose_name_plural': 'Registros de Prueba',
                'ordering': ['-creado_el'],
            },
        ),
    ]
